name: Exchange Wagyuswap Staging deployment - Test, Build & Deploy

on:
  push:
    branches: [staging]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.2]

    steps:
    - name: Start deployment
      uses: bobheadxi/deployments@master
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: Production

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Node Modules
      run: yarn

    - name: Lint Test
      run: yarn lint

    - name: Build
      run: yarn build

    - name: Upload to S3 and invalidate cloudfront
      uses: raulanatol/aws-s3-docker-action@v1.0.1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
        AWS_BUCKET_NAME: staging.exchange.wagyuswap.com
        SOURCE: ./build
        TARGET: ""
        WITH_DELETE: true
        WITH_CLOUD_FRONT_INVALIDATION: true
        AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CF_DISTRIBUTION_ID_STAGING_EXCHANGE_WAGYUSWAP }}
        AWS_CLOUDFRONT_INVALIDATION_PATH: "/*"

    - name: Update deployment status
      uses: bobheadxi/deployments@master
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
